### ISSUE TITLE
emacs freezes when opening new connection

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/cider#1311]
cider-20150909.2242, following is the flood from *Messages* when opening a new nrepl connection (via ```cider-jack-in```):

    Starting nREPL server via boot repl -s wait...
    nREPL server started on 59801
    nREPL: Establishing direct connection to localhost:59801 ...
    nREPL: Direct connection established
    Invalid face attribute :foreground nil [62 times]
    Invalid face reference: custom-button
    Invalid face attribute :foreground nil [2 times]
    Invalid face reference: custom-button
    Invalid face attribute :foreground nil [49 times]
    Invalid face reference: custom-button
    Invalid face attribute :foreground nil [2 times]
    Invalid face reference: custom-button
    Invalid face attribute :foreground nil [230 times]
    Invalid face reference: custom-button

    error in process filter: nrepl--pp: Wrong type argument: stringp, (dict "arglists" (("this")))
    error in process filter: Wrong type argument: stringp, (dict "arglists" (("this")))
    error in process filter: Quit [2 times]

there are _much_ more of these "invalid face" messages :) they all make Emacs horribly unresponsive for a while.

GNU Emacs 24.5.1 (x86_64-apple-darwin14.4.0, Carbon Version 157 AppKit 1348.17)

**Comment by Malabarba** [comment]
Thanks for reporting, shold be fixed now.
I'm not sure whether this will those `error in process filter`. If it doesn't, do let us know.

**Comment by mbuczko** [comment]
well, with cider-20150910.418 output has been reduced to:

    Invalid face attribute :foreground nil [1167 times]
    error in process filter: nrepl--pp: Wrong type argument: stringp, (dict "arglists" (("this")))
    error in process filter: Wrong type argument: stringp, (dict "arglists" (("this")))
    error in process filter: Quit [2 times]

and Emacs still gets frozen for a few minutes.

**Comment by bbatsov** [comment]
Seems that there's some expection in `nrepl--pp`. You can add a breakpoint there and debug it as mentioned the "Troubleshooting" section of the README.

**Comment by mbuczko** [comment]
ok, with cider-20150910.1006 the nrepl-pp problem magically disappeared. thanks guys, whatever you did ;)
