### ISSUE TITLE
Issue with cider-connect after remote REPL connection dies on OS X

### ISSUE THREAD

**Issue by aamedina** [clojure-emacs/cider#1313]
Steps to reproduce on OS X with latest CIDER available on Emacs:

1.) Start an nREPL server somewhere waiting for connections.
2.) M-x cider-connect to connect to it, providing the proper host and port if necessary. 
3.) Close the nREPL server connection by killing the process. (C-c works) Now restart it.
4.) M-x cider-connect will pop open a new CIDER REPL buffer successfully, but when you attempt to load code into it (via C-c C-k for example) you will see a message "selecting deleted buffer" in the Emacs echo pane. The only way to restore "normal" functionality appears to be a hard restart of Emacs. 

If you have any problems reproducing this issue let me know.

Thanks!

**Comment by Malabarba** [comment]
Could you issue a M-x toggle-debug-on-error? 
This will cause a backtrace to pop up when that error happens.

**Comment by aamedina** [comment]
The backtrace is for (error "Selecting deleted buffer"), triggering immediately after calling cider-find-connection-buffer-for-project-directory, which returns a "killed buffer".

**Comment by Malabarba** [comment]
@aamedina could you copy paste the backtrace here? :)

**Comment by Malabarba** [comment]
I just fixed a bug I was getting with dead buffers here as well. It may have fixed yours too. Let us know after upgrading from Melpa in a couple of hours.

**Comment by aamedina** [comment]
I upgraded and the problem remains.

**Comment by Malabarba** [comment]
@aamedina Just to be sure, did you restart Emacs after upgrading?

If so, then it would really help to see the backtrace you get.

**Comment by aamedina** [comment]
I still get the "Selecting deleted buffer" message in the echo pane, but toggle-debug-on-error no longer results in a backtrace. The problem otherwise remains though.

**Comment by aamedina** [comment]
Additionally another odd behavior I am noticing is the REPL seems laggy after printing that message. Also, no Clojure buffers seem able to find the current CIDER connection, even though the REPL is there and can evaluate code.

**Comment by Malabarba** [comment]
And all of these problems happen only after a connection dies and you reconnect?
Or do they happen right from the start?

**Comment by aamedina** [comment]
Only after a connection dies, upon a reconnect.

**Comment by aamedina** [comment]
After updating CIDER this morning it looks like the fix came through somewhere. Thanks! Closing the issue, will reopen if it resurfaces.
