### ISSUE TITLE
Invalid input in repl causes emacs to freeze

### ISSUE THREAD

**Issue by borjarus** [clojure-emacs/cider#1323]
When I write (defn sin-plus [a b]
(+ (* (Math/sin a) (Math/cos b)
and hit Enter emacs hangs and I can't do anything.
I have to kill emacs proces.

I try on Windows and Debian. Each of them have same Emacs version 24.5.1 and
CIDER 0.10.0snapshot (package: 20150913.1602) (Java 1.8.0_60, Clojure 1.7.0, nREP 0.2.10)

**Comment by Malabarba** [comment]
Is the lack of closing parens a typo or intentional?

**Comment by expez** [comment]
Here's the backtrace:
```
  forward-sexp(-1)
  clojure--looking-at-logical-sexp()
  clojure-forward-logical-sexp(1)
  forward-sexp(1)
  #[0 "\302\303!\210`\300W\205\304`\300\303\305$\210\301\211\242T\240\210\302\303!\210\202\207" [65139 (221281) forward-sexp 1 parse-partial-sexp t] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\303!\210`\300W\205\304`\300\303\305$\210\301\211\242T\240\210\302\303!\210\202\207" [65139 (221281) forward-sexp 1 parse-partial-sexp t] 5 "\n\n(fn)"])
  clojure-backtracking-indent(65139 (3 65110 65126 nil nil nil 0 nil nil (65086 65107 65110)) 6)
  clojure-indent-function(65139 (3 65110 65126 nil nil nil 0 nil nil (65086 65107 65110)))
  calculate-lisp-indent()
  lisp-indent-line()
  cider-repl-newline-and-indent()
  #[256 "\211\203\301 \207\302`\303\"\203`W\203\304!\210\305 \207\306d\"\203&\301\307!\207\310 \210\311\312!\207" [cider-repl-input-start-mark cider-repl--send-input get-text-property cider-old-input cider-repl--grab-old-input cider-repl--recenter-if-needed cider-repl--input-complete-p t cider-repl-newline-and-indent message "[input not complete]"] 4 ("/home/expez/.emacs.d/elpa/cider-20150911.253/cider-repl.elc" . 22255) "P"](nil)
  ad-Advice-cider-repl-return(#[256 "\211\203\301 \207\302`\303\"\203`W\203\304!\210\305 \207\306d\"\203&\301\307!\207\310 \210\311\312!\207" [cider-repl-input-start-mark cider-repl--send-input get-text-property cider-old-input cider-repl--grab-old-input cider-repl--recenter-if-needed cider-repl--input-complete-p t cider-repl-newline-and-indent message "[input not complete]"] 4 ("/home/expez/.emacs.d/elpa/cider-20150911.253/cider-repl.elc" . 22255) "P"] nil)
  apply(ad-Advice-cider-repl-return #[256 "\211\203\301 \207\302`\303\"\203`W\203\304!\210\305 \207\306d\"\203&\301\307!\207\310 \210\311\312!\207" [cider-repl-input-start-mark cider-repl--send-input get-text-property cider-old-input cider-repl--grab-old-input cider-repl--recenter-if-needed cider-repl--input-complete-p t cider-repl-newline-and-indent message "[input not complete]"] 4 ("/home/expez/.emacs.d/elpa/cider-20150911.253/cider-repl.elc" . 22255) "P"] nil)
  cider-repl-return(nil)
  call-interactively(cider-repl-return nil nil)
  command-execute(cider-repl-return)
```

@borjarus While CIDER shouldn't hang you're also evaluating invalid code.  You can get on with what you're been doing if you change:

```clj
(defn sin-plus [a b]
(+ (* (Math/sin a) (Math/cos b)
```

to

```
(defn sin-plus [a b]
  (+ (* (Math/sin a) (Math/cos b))))
```

**Comment by borjarus** [comment]
@expez Yes you have right but i used fragment of function, whole looks like this:

```clojure
(defn sin-plus [a b]
(+ (* (Math/sin a) (Math/cos b))
(* (Math/sin b) (Math/cos a))))
```

In repl I could write entire function inline and there would not be a nuisance.
But when I try to write this in cider-scratch I get same sittuation.
And there is more painful.

**Comment by expez** [comment]
@borjarus Could you describe the problem you're having with cider-scratch?  

```clj
;; This buffer is for Clojure experiments and evaluation.
;; Press C-j to evaluate the last expression.

(defn sin-plus [a b]
	(+ (* (Math/sin a) (Math/cos b))
		 (* (Math/sin b) (Math/cos a))))
#'user/sin-plus

(sin-plus 1 1)
0.9092974268256818
```

All I did was copy-paste and hit <kbd>C-j</kbd>. Everything seems to work as it should for me.

**Comment by borjarus** [comment]
try to not copy/paste but insert letter by letter (with disabled emacs modes like paraedit, smartparents etc.). In my case after i wrote 
(defn sin-plus [a b]
    (+ (* (Math/sin a) (Math/cos b)) this fragment emacs crash.

**Comment by expez** [comment]
Ah, that problem should be fixed by the patch @Malabarba applied, and I can't reproduce it anymore.  

Feel free to re-open if I'm mistaken.

Thanks for the bug report @borjarus!

**Comment by borjarus** [comment]
i 've got same situation when i write in repl 
(take 10 and then click enter. emacs again crash

**Comment by brettkromkamp** [comment]
Seeing the same behavior: pressing return with an incomplete expression causes the REPL to freeze. The debugger seems to be pointing at the "cider-repl-return" function.

**Comment by skc** [comment]
C-j (cider-repl-newline-and-indent) still hangs ..

; CIDER 0.10.0snapshot (package: 20150925.725) (Java 1.8.0_25, Clojure 1.7.0, nREPL 0.2.10)
user> (+ 1 2

**Comment by Malabarba** [comment]
This is still an issue with clojure-mode's sexp navigation. It affects plain clojure buffers. I'm trying ot fix.

**Comment by expez** [comment]
@skc @borjarus @brettkromkamp It might seem weird to you guys that this actually is an issue but it's extremely uncommon for anyone to be editing lisp code in emacs without using either [paredit](http://www.emacswiki.org/emacs/ParEdit) or [smartparens](https://github.com/Fuco1/smartparens) which automatically inserts closing parenthesis etc for you so this is the first we've heard of it :/

We'll get this fixed but I'd like to highly recommend that you check out one of these packages.  To quote Phil Hagelberg, of leiningen fame:

> If paredit is not for you, then you need to become the sort of person that paredit is for.

Here's some motivational material:

[emacs rocks episode on paredit](http://emacsrocks.com/e14.html)
[animated guide to paredit](http://danmidwood.com/content/2014/11/21/animated-paredit.html)

I personally prefer smartparens to paredit, because it works in non-lisp contexts too, but both are wonderful packages.

**Comment by brettkromkamp** [comment]
@expez I know and I agree. It just seemed strange to me that something (seemingly) non-trivial as pressing return (admittedly, in an incomplete expression) could cause an editor to hang. 

Either way, I just want to thank you and everyone else who is contributing to this project. It really is a fantastic piece of software.

**Comment by skc** [comment]
@expez  I was't aware of those packages. 
Thanks.

**Comment by edmondo1984** [comment]
my emacs doesn't hang but he keeps showing input not complete, I can't get out from there hitting escape or c+g, what do you suggest?
