### ISSUE TITLE
Newest cider gives a "Wrong number of arguments" error

### ISSUE THREAD

**Issue by bsteuber** [clojure-emacs/cider#1349]
I get an "error in process filter: let: Wrong number of arguments: (4 . 6), 3" when trying cider-jack-in with cider 20150924.1202 on this project.clj:
(defproject bug "0.1.0-SNAPSHOT"  
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]])

I use Leiningen 2.5.3 and this happens with both (the in leiningen included) tools.nrepl 0.2.10 and tools.nrepl 0.2.11.
The repl does still work afterwards, but this bug breaks all clojurescript repls for me.

Any ideas?

**Comment by Malabarba** [comment]
M-x toggle-debug-on-error and show us the backtrace. 👍

**Comment by bsteuber** [comment]
Oh as it turns out this bug was our own problem in a hook that used an old cider-eval signature.
So I'll close this issue. The thing I'm still failing to accomplish is connecting cider to figwheel-0.4.0, but that's a different topic..

**Comment by Malabarba** [comment]
Have you tried this? https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Comment by bsteuber** [comment]
Yes I did. I've boiled my experiments down to this minimal failing project:
https://github.com/bsteuber/ciderfig
The problem might be the reagent.core dependency, without the require it
just works interestingly...

**Comment by Malabarba** [comment]
Ah, that's a bug I fixed today. See clojure-emacs/cider-nrepl#260.
Haven't pushed the snapshot yet, though.

**Comment by bsteuber** [comment]
Ah great, please ping me when it's there ^^

**Comment by Malabarba** [comment]
It's up now. Let me know if it works.

**Comment by bsteuber** [comment]
Nope, still fails with cider-nrepl-0.10.0-20150926.081655-31 and cider
20150925.725 for me. You can try reproducing it yourself with
https://github.com/bsteuber/ciderfig just to be sure.

Another question, back to my first problem: How do I use cider-eval (or
nrepl-eval) in order to start the cljs-repl automatically? I'm trying

(defun cider-start-browser-repl ()
  (interactive)
  (cider-eval
    "(do (use 'figwheel-sidecar.repl-api) (cljs-repl))"
    (lambda (x) (message "connected"))
    (cider-current-connection)
    (cider-current-session))))

which prints "connected" but doesn't start an actual cljs repl. Any idea?

Thx,
Benjamin

**Comment by TreeRex** [comment]
I was getting this error as well.

It turns out that DIME (Dylan Interaction Mode for Emacs), included with dylan-mode,  defines a `when-let` macro globally using `cl-defmacro`:

    (cl-defmacro when-let ((var value) &rest body)
      "Evaluate VALUE, if the result is non-nil bind it to VAR and eval BODY.
    
    \(fn (VAR VALUE) &rest BODY)"
      (declare (indent 1))
      `(let ((,var ,value))
         (when ,var ,@body)))

The version defined in cider-compat.el has different semantics (supporting multiple bindings) but is not defined because of the `fboundp` check.

I'm not working with Dylan now, so I am just going to remove dylan-mode from my configuration.

**Comment by Malabarba** [comment]
Could you please file an issue with them too? They're redefining a macro that's built-in in Emacs 25, but they're using an incompatible definition. That's going to cause problems with a lot more packages than just cider.
