### ISSUE TITLE
Unexpected exception when using REPL without a project

### ISSUE THREAD

**Issue by ksseono** [clojure-emacs/cider#2470]
## Expected behavior
REPL runs without an exception when running without a project.

## Actual behavior
Normally, I've got an exception as below: 
```
java.lang.IllegalArgumentException: No method in multimethod 'op-handler' for dispatch value: null
 at clojure.lang.MultiFn.getFn (MultiFn.java:156)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    cider.nrepl.middleware.util.error_handling$eval2592$fn__2593.invoke (error_handling.clj:162)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    cider.nrepl.middleware.out$handle_out.invokeStatic (out.clj:127)
    cider.nrepl.middleware.out$handle_out.invoke (out.clj:126)
    clojure.lang.Var.invoke (Var.java:383)
    cider.nrepl$wrap_out$fn__2093.invoke (nrepl.clj:336)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_refresh$fn__2109.invoke (nrepl.clj:382)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_macroexpand$fn__2077.invoke (nrepl.clj:295)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_stacktrace$fn__2133.invoke (nrepl.clj:436)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_inspect$fn__2069.invoke (nrepl.clj:255)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_apropos$fn__2009.invoke (nrepl.clj:158)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_classpath$fn__2017.invoke (nrepl.clj:166)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_content_type$fn__1993.invoke (nrepl.clj:139)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_info$fn__2059.invoke (nrepl.clj:236)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    cider.nrepl$wrap_format$fn__2051.invoke (nrepl.clj:222)
    nrepl.middleware$wrap_conj_descriptor$fn__1410.invoke (middleware.clj:15)
    clojure.tools.nrepl.server$handle_STAR_.invokeStatic (server.clj:19)
    clojure.tools.nrepl.server$handle_STAR_.invoke (server.clj:16)
    clojure.tools.nrepl.server$handle$fn__5664.invoke (server.clj:28)
    clojure.core$binding_conveyor_fn$fn__4676.invoke (core.clj:1938)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:264)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
    java.lang.Thread.run (Thread.java:844)
```

Sometimes, it runs without the error but it doesn't evaluate any of codes.  

```
user> (+ 1 2)
;; (it stops here and when I press enter key, prompt appears again)
user> 
```

## Steps to reproduce the problem
1. add a line below in `.spacemacs` (currently I'm using Spacemacs)
   : `(setq cider-jack-in-default 'lein)`

2. excute `cider-jack-in`

### CIDER version information

```
;; CIDER 0.18.1snapshot (package: 20180926.1025), nREPL 0.2.12
;; Clojure 1.8.0, Java 9.0.4
```

### Lein/Boot version

* Leiningen 2.8.1 on Java 9.0.4 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

* GNU Emacs 25.3.1 (x86_64-apple-darwin17.0.0) of 2017-09-16
* using Spacemacs (develop branch)
  * added `clojure` layer in `dotspacemacs-configuration-layers`

### Operating system

* macOS Mojave (10.14)

**Comment by bbatsov** [comment]
What's your version of cider-nrepl?

**Comment by ksseono** [comment]
@bbatsov I don't set-up the exact version of cider-nrepl in `profiles.clj` for Leiningen, but it seems like CIDER is injecting cider-nrepl 0.18.0 as a plugin, since I can see a log message below. 

```
[nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0\"\] -- repl :headless :host ::...
```

**Comment by bbatsov** [comment]
Good. 

Can you post here what do you have in your `profiles.clj` and also try running same command to start lein outside Emacs?

**Comment by ksseono** [comment]
My profiles.clj is here: 

```
{:user {:plugins [[jonase/eastwood "0.2.9"]
                  [lein-pprint "1.2.0"]
                  [lein-localrepo "0.5.4"]]
        :dependencies [[slamhound "1.5.5"]
                       [acyclic/squiggly-clojure "0.1.6"]
                       [philoskim/debux "0.5.1"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
```

When I've tried run outside Emacs without a project, with this command: 

```
/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0\"\] -- repl
```

and it seems like it cannot find `cider.nrepl`

```
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-apropos, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-classpath, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-complete, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-debug, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-enlighten, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-format, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-info, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-inspect, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-macroexpand, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-ns, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-out, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-content-type, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-slurp, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-pprint-fn, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-profile, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-refresh, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-resource, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-spec, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-stacktrace, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-test, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-trace, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-tracker, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-undef, see clojure.tools.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/wrap-version, see clojure.tools.middleware/set-descriptor!
nREPL server started on port 50857 on host 127.0.0.1 - nrepl://127.0.0.1:50857
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cider.inlined_deps.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval3583$fn__3584 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of cider.inlined_deps.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval3583$fn__3584
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=>
```

**Comment by bbatsov** [comment]
Yeah, I expected as much. Please comment out everything in the profiles and try again. 99% one of the packages there is messing up the way in which the nREPL dep is loaded, but I'm not sure which one.

**Comment by bbatsov** [comment]
See also https://github.com/clojure-emacs/cider/issues/2459, which is probably related.

**Comment by ksseono** [comment]
hmm.. sadly, I've made my profiles.clj clear and tried again, but the same problems has arisen.

**Comment by bbatsov** [comment]
Hmm, perhaps your issue is similar to that one https://github.com/clojure-emacs/cider/issues/2459?

**Comment by ksseono** [comment]
Well, I'm not sure as I couldn't find any of system component which is using CIDER. One thing I've found is here. 

With `cider-nrepl 0.17.0`, it seems like working excepting warning messages which are about illegal reflective access, 
```
/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0\"\] -- repl
Retrieving cider/cider-nrepl/0.17.0/cider-nrepl-0.17.0.pom from clojars
Retrieving cider/cider-nrepl/0.17.0/cider-nrepl-0.17.0.jar from clojars
nREPL server started on port 55112 on host 127.0.0.1 - nrepl://127.0.0.1:55112
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cider.inlined_deps.orchard.v0v2v0.dynapath.v0v2v5.dynapath.defaults$eval3999$fn__4000 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of cider.inlined_deps.orchard.v0v2v0.dynapath.v0v2v5.dynapath.defaults$eval3999$fn__4000
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=>
```

and with `cider-nrepl 0.16.0`, it's perfectly working. 
```
/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.16.0\"\] -- repl
nREPL server started on port 55132 on host 127.0.0.1 - nrepl://127.0.0.1:55132
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=>
```

even I'm not sure about this line in common for both cases: `REPL-y 0.3.7, nREPL 0.2.12`.

**Comment by bbatsov** [comment]
cider-nrepl used to have a hard depedency to tools.nrepl before version 0.18, but now it has to infer the version of nREPL used dynamically. Seem something like:

https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/stacktrace.clj#L17

What's happening for you is that somehow `find-ns` for tools.nrepl fails for you and cider-nrepl loads the classes from the new nREPL server, but lein starts for you the old one. So there must be some code that gets executed before the REPL starts.

**Comment by ksseono** [comment]
Yes, indeed. Since when I've tested with clojure itself,
```
[nREPL] Starting server via /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.4.5"} refactor-nrepl {:mvn/version "2.4.0"} cider/cider-nrepl {:mvn/version "0.18.0"}}}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["cider.nrepl/cider-middleware"])'...
```
it's working with nREPL 0.4.5.
```
;; Connected to nREPL server - nrepl://localhost:49428
;; CIDER 0.18.1snapshot (package: 20180930.1836), nREPL 0.4.5
;; Clojure 1.9.0, Java 9.0.4
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
user> 
```

But with lein, it seems like failing to load the new one as you said.
```
[nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0\"\] -- repl :headless :host ::...
```
```
;; Connected to nREPL server - nrepl://localhost:49426
;; CIDER 0.18.1snapshot (package: 20180930.1836), nREPL 0.2.12
;; Clojure 1.9.0, Java 9.0.4
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
user> 
```

I think I'm almost getting the point with your kind help, but I'm afraid that I couldn't find a way to track any of codes that gets excuted before the REPL starts. There's no processes using CIDER, nREPL, or Leiningen before the REPL excuting and it seems not any of external dependencies is interrupting. 

What points do you think that I should check further?

**Comment by ksseono** [comment]
It seems like REPL is just following Leiningen's dependency. 
When I tested with 2.8.2 built from Leiningen project which has `[nrepl "0.4.3"]` as a dependency, no errors occurred. But when I use Leiningen 2.8.1 which is a stable version and has `[org.clojure/tools.nrepl "0.2.12"]` [as its dependency](https://github.com/technomancy/leiningen/blob/2.8.1/project.clj), it's working with the version.

I think the root cause of this issue is that Leiningen REPL is not using the dependencies passed from the command line options, like `update-in :dependencies conj \[nrepl\ \"0.4.5\"\]`. 

What do you think?

**Comment by bbatsov** [comment]
Yeah, as the artefact name changed we can't override the old nREPL prior to 2.8.2. This injection is most for the future, not for the present. 

CIDER is still able to work with nREPL 0.2, but for some reason the dependency order gets totally messed for you. Hopefully `lein` 2.8.2 will be released soon and life will become simpler for everyone.

**Comment by ksseono** [comment]
It seems like this issue has been resolved by [Leingen 2.5.3](https://github.com/technomancy/leiningen/releases/tag/2.8.3?fbclid=IwAR3LdmhVVzHd-TqIDyik6L73lTyuaxx4We6BlUYib0E-J7jCjhLoDPuDTjw) which is released Dec 14th. It's working with `[nrepl "0.5.3"]` without a project and no errors happened. 

```
;; Connected to nREPL server - nrepl://localhost:58337
;; CIDER 0.19.0snapshot (package: 20181128.1311), nREPL 0.5.3
;; Clojure 1.8.0, Java 11.0.1
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
user> (+ 1 2)
3
user> 
```

**Comment by bbatsov** [comment]
Yeah, lein 2.8.3 finally ships a modern nREPL.

**Comment by ksseono** [comment]
OK, then. I can close this issue now. Thanks @bbatsov :)

**Comment by LeaveNhA** [comment]
I think, this problem is still there.
Leiningen 2.9.3, no profile.clj file provided. No repl starts.

**Comment by dpsutton** [comment]
i'm not sure there is a lein 2.9.3? Do you mean 2.8.3? I think the latest is 2.9.1
