### ISSUE TITLE
Issue with refresh operation after updating to nrepl `1.3.0-beta2`

### ISSUE THREAD

**Issue by rrudakov** [clojure-emacs/cider#3727]
## Expected behavior

Execution `M-x cider-ns-refresh` or `C-c M-n r` works successfully.

## Actual behavior

Operation fails for some project with the following error:
```
Unhandled java.lang.IllegalArgumentException
   No implementation of method: :send of protocol:
   #'nrepl.transport/Transport found for class: nil
```

## Steps to reproduce the problem

Unfortunately I couldn't reproduce it on a dummy test project, but I can reproduce it consistently on a real project which I cannot share.

Starting CIDER with nrepl 1.2.0 fixes the issue for me, so I guess it's related to the recent changes in the nrepl code.

### 

<details>
<summary>Exception with stacktrace</summary>

```
2. Unhandled java.lang.IllegalArgumentException
   No implementation of method: :send of protocol:
   #'nrepl.transport/Transport found for class: nil

          core_deftype.clj:  584  clojure.core/-cache-protocol-fn
          core_deftype.clj:  576  clojure.core/-cache-protocol-fn
             transport.clj:   25  nrepl.transport/eval23784/fn/G
                 print.clj:   70  nrepl.middleware.print/replying-PrintWriter/fn
       CallbackWriter.java:   39  nrepl.CallbackWriter/write
       CallbackWriter.java:   26  nrepl.CallbackWriter/write
       BufferedWriter.java:  178  java.io.BufferedWriter/implFlushBuffer
       BufferedWriter.java:  169  java.io.BufferedWriter/flushBuffer
       BufferedWriter.java:  371  java.io.BufferedWriter/implFlush
       BufferedWriter.java:  365  java.io.BufferedWriter/flush
          PrintWriter.java:  426  java.io.PrintWriter/implFlush
          PrintWriter.java:  418  java.io.PrintWriter/flush
               encore.cljc: 3914  taoensso.encore$println_atomic/invokeStatic
               encore.cljc: 3902  taoensso.encore$println_atomic/invoke
                      REPL:   57  user/println-ctx-aware-appender/fn
               timbre.cljc:  601  taoensso.timbre$_log_BANG_$fn__5245/invoke
   PersistentArrayMap.java:  429  clojure.lang.PersistentArrayMap/kvreduce
                  core.clj: 6909  clojure.core/fn
                  core.clj: 6889  clojure.core/fn
             protocols.clj:  175  clojure.core.protocols/fn/G
                  core.clj: 6920  clojure.core/reduce-kv
                  core.clj: 6911  clojure.core/reduce-kv
               timbre.cljc:  550  taoensso.timbre$_log_BANG_/invokeStatic
               timbre.cljc:  455  taoensso.timbre$_log_BANG_/invoke
                config.clj:   16  app.system.config/load-config
                config.clj:   10  app.system.config/load-config
                  AFn.java:  156  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
             Compiler.java: 3714  clojure.lang.Compiler$InvokeExpr/eval
             Compiler.java: 3713  clojure.lang.Compiler$InvokeExpr/eval
             Compiler.java:  457  clojure.lang.Compiler$DefExpr/eval
             Compiler.java: 7199  clojure.lang.Compiler/eval
             Compiler.java: 7653  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6162  clojure.core/load/fn
                  core.clj: 6161  clojure.core/load
                  core.clj: 6145  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5934  clojure.core/load-one
                  core.clj: 5929  clojure.core/load-one
                  core.clj: 5976  clojure.core/load-lib/fn
                  core.clj: 5975  clojure.core/load-lib
                  core.clj: 5954  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 6017  clojure.core/load-libs
                  core.clj: 6001  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 6039  clojure.core/require
                  core.clj: 6039  clojure.core/require
               RestFn.java:  421  clojure.lang.RestFn/invoke
                reload.clj:   35  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one
                reload.clj:   21  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one
                reload.clj:   52  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload
                reload.clj:   43  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload
               refresh.clj:  101  cider.nrepl.middleware.refresh/refresh-reply/fn/fn
               refresh.clj:   91  cider.nrepl.middleware.refresh/refresh-reply/fn
               session.clj:  234  nrepl.middleware.session/session-exec/session-loop
        SessionThread.java:   21  nrepl.SessionThread/run

1. Caused by clojure.lang.Compiler$CompilerException
   Error compiling system.clj at (9:7)
   #:clojure.error{:phase :execution,
                   :line 9,
                   :column 7,
                   :source "system.clj"}
             Compiler.java: 3719  clojure.lang.Compiler$InvokeExpr/eval
             Compiler.java: 3713  clojure.lang.Compiler$InvokeExpr/eval
             Compiler.java:  457  clojure.lang.Compiler$DefExpr/eval
             Compiler.java: 7199  clojure.lang.Compiler/eval
             Compiler.java: 7653  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6162  clojure.core/load/fn
                  core.clj: 6161  clojure.core/load
                  core.clj: 6145  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5934  clojure.core/load-one
                  core.clj: 5929  clojure.core/load-one
                  core.clj: 5976  clojure.core/load-lib/fn
                  core.clj: 5975  clojure.core/load-lib
                  core.clj: 5954  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 6017  clojure.core/load-libs
                  core.clj: 6001  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 6039  clojure.core/require
                  core.clj: 6039  clojure.core/require
               RestFn.java:  421  clojure.lang.RestFn/invoke
                reload.clj:   35  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one
                reload.clj:   21  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one
                reload.clj:   52  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload
                reload.clj:   43  cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload
               refresh.clj:  101  cider.nrepl.middleware.refresh/refresh-reply/fn/fn
               refresh.clj:   91  cider.nrepl.middleware.refresh/refresh-reply/fn
               session.clj:  234  nrepl.middleware.session/session-exec/session-loop
        SessionThread.java:   21  nrepl.SessionThread/run
```

</details>

<details>
<summary>nrepl messages</summary>

```
(-->
  id                                 "13"
  op                                 "refresh"
  session                            "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp                         "2024-07-22 14:23:38.176480000"
  nrepl.middleware.print/buffer-size 4096

  nrepl.middleware.print/options     (dict ...)
  nrepl.middleware.print/print       "cider.nrepl.pprint/pprint"
  nrepl.middleware.print/quota       1048576

  nrepl.middleware.print/stream?     "1"
)
(<--
  id         "13"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:38.336581000"
  reloading  ("app.db.sql.google-analytics-events-test" ...)
)
(<--
  id                 "11"
  session            "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp         "2024-07-22 14:23:38.855026000"
  changed-namespaces (dict ...)
  repl-type          "clj"
  status             ("state")
)
(<--
  id         "13"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:38.951574000"
  error      ((dict "class" "clojure.lang.Compiler$CompilerException" "column" 7
       "compile-like" "false" "data"
       "#:clojure.error{:phase :execution,\n                :line 9,\n                :column 7,\n                :source \"system.clj\"}"
       "file" "system.clj" "file-url" nil "line" 9 "location"
       (dict "clojure.error/column" 7 "clojure.error/line" 9
             "clojure.error/phase" "execution" "clojure.error/source"
             "system.clj")
       "message" "Syntax error macroexpanding at (system.clj:9:7)."
       "path" "system.clj" "phase" "execution" "stacktrace"
       ((dict "class" "clojure.lang.Compiler$InvokeExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("tooling" "java") "line" 3719 "method" "eval" "name"
              "clojure.lang.Compiler$InvokeExpr/eval" "type" "java")
        (dict "class" "clojure.lang.Compiler$InvokeExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("dup" "tooling" "java") "line" 3713 "method" "eval"
              "name" "clojure.lang.Compiler$InvokeExpr/eval" "type"
              "java")
        (dict "class" "clojure.lang.Compiler$DefExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("tooling" "java") "line" 457 "method" "eval" "name"
              "clojure.lang.Compiler$DefExpr/eval" "type" "java")
        (dict "class" "clojure.lang.Compiler" "file" "Compiler.java"
              "file-url" nil "flags" ("tooling" "java") "line" 7199
              "method" "eval" "name" "clojure.lang.Compiler/eval"
              "type" "java")
        (dict "class" "clojure.lang.Compiler" "file" "Compiler.java"
              "file-url" nil "flags" ("tooling" "java") "line" 7653
              "method" "load" "name" "clojure.lang.Compiler/load"
              "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("tooling" "java") "line" 381 "method"
              "loadResourceScript" "name"
              "clojure.lang.RT/loadResourceScript" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("dup" "tooling" "java") "line" 372 "method"
              "loadResourceScript" "name"
              "clojure.lang.RT/loadResourceScript" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("tooling" "java") "line" 459 "method"
              "load" "name" "clojure.lang.RT/load" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("dup" "tooling" "java") "line" 424 "method"
              "load" "name" "clojure.lang.RT/load" "type" "java")
        (dict "class" "clojure.core$load$fn__6908" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load/fn" "line" 6162 "method"
              "invoke" "name" "clojure.core$load$fn__6908/invoke" "ns"
              "clojure.core" "type" "clj" "var" "clojure.core/load")
        (dict "class" "clojure.core$load" "file" "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load" "line" 6161 "method"
              "invokeStatic" "name" "clojure.core$load/invokeStatic"
              "ns" "clojure.core" "type" "clj" "var"
              "clojure.core/load")
        (dict "class" "clojure.core$load" "file" "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load" "line" 6145 "method"
              "doInvoke" "name" "clojure.core$load/doInvoke" "ns"
              "clojure.core" "type" "clj" "var" "clojure.core/load")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 408
              "method" "invoke" "name" "clojure.lang.RestFn/invoke"
              "type" "java")
        (dict "class" "clojure.core$load_one" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-one" "line" 5934 "method"
              "invokeStatic" "name"
              "clojure.core$load_one/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/load-one")
        (dict "class" "clojure.core$load_one" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-one" "line" 5929 "method"
              "invoke" "name" "clojure.core$load_one/invoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-one")
        (dict "class" "clojure.core$load_lib$fn__6850" "file"
              "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib/fn" "line" 5976 "method"
              "invoke" "name" "clojure.core$load_lib$fn__6850/invoke"
              "ns" "clojure.core" "type" "clj" "var"
              "clojure.core/load-lib")
        (dict "class" "clojure.core$load_lib" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib" "line" 5975 "method"
              "invokeStatic" "name"
              "clojure.core$load_lib/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/load-lib")
        (dict "class" "clojure.core$load_lib" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib" "line" 5954 "method"
              "doInvoke" "name" "clojure.core$load_lib/doInvoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-lib")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 142
              "method" "applyTo" "name" "clojure.lang.RestFn/applyTo"
              "type" "java")
        (dict "class" "clojure.core$apply" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("tooling" "clj") "fn" "apply" "line" 669
              "method" "invokeStatic" "name"
              "clojure.core$apply/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/apply")
        (dict "class" "clojure.core$load_libs" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-libs" "line" 6017 "method"
              "invokeStatic" "name"
              "clojure.core$load_libs/invokeStatic" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-libs")
        (dict "class" "clojure.core$load_libs" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-libs" "line" 6001 "method"
              "doInvoke" "name" "clojure.core$load_libs/doInvoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-libs")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 137
              "method" "applyTo" "name" "clojure.lang.RestFn/applyTo"
              "type" "java")
        (dict "class" "clojure.core$apply" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("tooling" "clj") "fn" "apply" "line" 669
              "method" "invokeStatic" "name"
              "clojure.core$apply/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/apply")
        (dict "class" "clojure.core$require" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "require" "line" 6039 "method"
              "invokeStatic" "name"
              "clojure.core$require/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/require")
        (dict "class" "clojure.core$require" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("dup" "clj") "fn" "require" "line" 6039
              "method" "doInvoke" "name"
              "clojure.core$require/doInvoke" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/require")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 421
              "method" "invoke" "name" "clojure.lang.RestFn/invoke"
              "type" "java")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload-one" "line"
              35 "method" "invokeStatic" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one/invokeStatic"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload-one" "line"
              21 "method" "invoke" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one/invoke"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload" "line" 52
              "method" "invokeStatic" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload/invokeStatic"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload" "line" 43
              "method" "invoke" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload/invoke"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload")
        (dict "class"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297$fn__129298"
              "file" "refresh.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/middleware/refresh.clj"
              "flags" ("tooling" "clj") "fn" "refresh-reply/fn/fn"
              "line" 101 "method" "invoke" "name"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297$fn__129298/invoke"
              "ns" "cider.nrepl.middleware.refresh" "type" "clj" "var"
              "cider.nrepl.middleware.refresh/refresh-reply")
        (dict "class"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297"
              "file" "refresh.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/middleware/refresh.clj"
              "flags" ("tooling" "clj") "fn" "refresh-reply/fn" "line"
              91 "method" "invoke" "name"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297/invoke"
              "ns" "cider.nrepl.middleware.refresh" "type" "clj" "var"
              "cider.nrepl.middleware.refresh/refresh-reply")
        (dict "class"
              "nrepl.middleware.session$session_exec$session_loop__24462"
              "file" "session.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/nrepl/nrepl/1.3.0-beta2/nrepl-1.3.0-beta2.jar!/nrepl/middleware/session.clj"
              "flags" ("tooling" "clj") "fn"
              "session-exec/session-loop" "line" 234 "method" "invoke"
              "name"
              "nrepl.middleware.session$session_exec$session_loop__24462/invoke"
              "ns" "nrepl.middleware.session" "type" "clj" "var"
              "nrepl.middleware.session/session-exec")
        (dict "class" "nrepl.SessionThread" "file"
              "SessionThread.java" "file-url" nil "flags"
              ("tooling" "java") "line" 21 "method" "run" "name"
              "nrepl.SessionThread/run" "type" "java")))
 (dict "class" "java.lang.IllegalArgumentException" "compile-like"
       "false" "message"
       "No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: nil"
       "phase" nil "stacktrace"
       ((dict "class" "clojure.core$_cache_protocol_fn" "file"
              "core_deftype.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core_deftype.clj"
              "flags" ("clj") "fn" "-cache-protocol-fn" "line" 584
              "method" "invokeStatic" "name"
              "clojure.core$_cache_protocol_fn/invokeStatic" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/-cache-protocol-fn")
        (dict "class" "clojure.core$_cache_protocol_fn" "file"
              "core_deftype.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core_deftype.clj"
              "flags" ("clj") "fn" "-cache-protocol-fn" "line" 576
              "method" "invoke" "name"
              "clojure.core$_cache_protocol_fn/invoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/-cache-protocol-fn")
        (dict "class"
              "nrepl.transport$eval23784$fn__23802$G__23775__23809"
              "file" "transport.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/nrepl/nrepl/1.3.0-beta2/nrepl-1.3.0-beta2.jar!/nrepl/transport.clj"
              "flags" ("tooling" "clj") "fn" "eval23784/fn/G" "line"
              25 "method" "invoke" "name"
              "nrepl.transport$eval23784$fn__23802$G__23775__23809/invoke"
              "ns" "nrepl.transport" "type" "clj" "var"
              "nrepl.transport/eval23784")
        (dict "class"
              "nrepl.middleware.print$replying_PrintWriter$fn__24285"
              "file" "print.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/nrepl/nrepl/1.3.0-beta2/nrepl-1.3.0-beta2.jar!/nrepl/middleware/print.clj"
              "flags" ("tooling" "clj") "fn" "replying-PrintWriter/fn"
              "line" 70 "method" "invoke" "name"
              "nrepl.middleware.print$replying_PrintWriter$fn__24285/invoke"
              "ns" "nrepl.middleware.print" "type" "clj" "var"
              "nrepl.middleware.print/replying-PrintWriter")
        (dict "class" "nrepl.CallbackWriter" "file"
              "CallbackWriter.java" "file-url" nil "flags"
              ("tooling" "java") "line" 39 "method" "write" "name"
              "nrepl.CallbackWriter/write" "type" "java")
        (dict "class" "nrepl.CallbackWriter" "file"
              "CallbackWriter.java" "file-url" nil "flags"
              ("dup" "tooling" "java") "line" 26 "method" "write"
              "name" "nrepl.CallbackWriter/write" "type" "java")
        (dict "class" "java.io.BufferedWriter" "file"
              "BufferedWriter.java" "file-url" nil "flags" ("java")
              "line" 178 "method" "implFlushBuffer" "name"
              "java.io.BufferedWriter/implFlushBuffer" "type" "java")
        (dict "class" "java.io.BufferedWriter" "file"
              "BufferedWriter.java" "file-url" nil "flags" ("java")
              "line" 169 "method" "flushBuffer" "name"
              "java.io.BufferedWriter/flushBuffer" "type" "java")
        (dict "class" "java.io.BufferedWriter" "file"
              "BufferedWriter.java" "file-url" nil "flags" ("java")
              "line" 371 "method" "implFlush" "name"
              "java.io.BufferedWriter/implFlush" "type" "java")
        (dict "class" "java.io.BufferedWriter" "file"
              "BufferedWriter.java" "file-url" nil "flags" ("java")
              "line" 365 "method" "flush" "name"
              "java.io.BufferedWriter/flush" "type" "java")
        (dict "class" "java.io.PrintWriter" "file" "PrintWriter.java"
              "file-url" nil "flags" ("java") "line" 426 "method"
              "implFlush" "name" "java.io.PrintWriter/implFlush"
              "type" "java")
        (dict "class" "java.io.PrintWriter" "file" "PrintWriter.java"
              "file-url" nil "flags" ("java") "line" 418 "method"
              "flush" "name" "java.io.PrintWriter/flush" "type" "java")
        (dict "class" "taoensso.encore$println_atomic" "file"
              "encore.cljc" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/com/taoensso/encore/3.85.0/encore-3.85.0.jar!/taoensso/encore.cljc"
              "flags" ("cljc") "fn" "println-atomic" "line" 3914
              "method" "invokeStatic" "name"
              "taoensso.encore$println_atomic/invokeStatic" "ns"
              "taoensso.encore" "type" "cljc" "var"
              "taoensso.encore/println-atomic")
        (dict "class" "taoensso.encore$println_atomic" "file"
              "encore.cljc" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/com/taoensso/encore/3.85.0/encore-3.85.0.jar!/taoensso/encore.cljc"
              "flags" ("cljc") "fn" "println-atomic" "line" 3902
              "method" "invoke" "name"
              "taoensso.encore$println_atomic/invoke" "ns"
              "taoensso.encore" "type" "cljc" "var"
              "taoensso.encore/println-atomic")
        (dict "class" "user$println_ctx_aware_appender$fn__126862"
              "file" "NO_SOURCE_FILE" "file-url" "" "flags"
              ("project" "repl" "clj") "fn"
              "println-ctx-aware-appender/fn" "line" 57 "method"
              "invoke" "name"
              "user$println_ctx_aware_appender$fn__126862/invoke" "ns"
              "user" "type" "clj" "var"
              "user/println-ctx-aware-appender")
        (dict "class" "taoensso.timbre$_log_BANG_$fn__5245" "file"
              "timbre.cljc" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/com/taoensso/timbre/6.5.0/timbre-6.5.0.jar!/taoensso/timbre.cljc"
              "flags" ("cljc") "fn" "-log!/fn" "line" 601 "method"
              "invoke" "name"
              "taoensso.timbre$_log_BANG_$fn__5245/invoke" "ns"
              "taoensso.timbre" "type" "cljc" "var"
              "taoensso.timbre/-log!")
        (dict "class" "clojure.lang.PersistentArrayMap" "file"
              "PersistentArrayMap.java" "file-url" nil "flags"
              ("java") "line" 429 "method" "kvreduce" "name"
              "clojure.lang.PersistentArrayMap/kvreduce" "type" "java")
        (dict "class" "clojure.core$fn__8525" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "fn" "line" 6909 "method"
              "invokeStatic" "name"
              "clojure.core$fn__8525/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/fn")
        (dict "class" "clojure.core$fn__8525" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "fn" "line" 6889 "method" "invoke"
              "name" "clojure.core$fn__8525/invoke" "ns"
              "clojure.core" "type" "clj" "var" "clojure.core/fn")
        (dict "class" "clojure.core.protocols$fn__8257$G__8252__8266"
              "file" "protocols.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core/protocols.clj"
              "flags" ("tooling" "clj") "fn" "fn/G" "line" 175
              "method" "invoke" "name"
              "clojure.core.protocols$fn__8257$G__8252__8266/invoke"
              "ns" "clojure.core.protocols" "type" "clj" "var"
              "clojure.core.protocols/fn")
        (dict "class" "clojure.core$reduce_kv" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "reduce-kv" "line" 6920 "method"
              "invokeStatic" "name"
              "clojure.core$reduce_kv/invokeStatic" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/reduce-kv")
        (dict "class" "clojure.core$reduce_kv" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "reduce-kv" "line" 6911 "method"
              "invoke" "name" "clojure.core$reduce_kv/invoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/reduce-kv")
        (dict "class" "taoensso.timbre$_log_BANG_" "file"
              "timbre.cljc" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/com/taoensso/timbre/6.5.0/timbre-6.5.0.jar!/taoensso/timbre.cljc"
              "flags" ("cljc") "fn" "-log!" "line" 550 "method"
              "invokeStatic" "name"
              "taoensso.timbre$_log_BANG_/invokeStatic" "ns"
              "taoensso.timbre" "type" "cljc" "var"
              "taoensso.timbre/-log!")
        (dict "class" "taoensso.timbre$_log_BANG_" "file"
              "timbre.cljc" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/com/taoensso/timbre/6.5.0/timbre-6.5.0.jar!/taoensso/timbre.cljc"
              "flags" ("cljc") "fn" "-log!" "line" 455 "method"
              "invoke" "name" "taoensso.timbre$_log_BANG_/invoke" "ns"
              "taoensso.timbre" "type" "cljc" "var"
              "taoensso.timbre/-log!")
        (dict "class" "app.system.config$load_config" "file"
              "config.clj" "file-url"
              "file:/Users/rrudakov/Work/adgoji-campaign-server-proto/src/clj/app/system/config.clj"
              "flags" ("project" "clj") "fn" "load-config" "line" 16
              "method" "invokeStatic" "name"
              "app.system.config$load_config/invokeStatic" "ns"
              "app.system.config" "type" "clj" "var"
              "app.system.config/load-config")
        (dict "class" "app.system.config$load_config" "file"
              "config.clj" "file-url"
              "file:/Users/rrudakov/Work/adgoji-campaign-server-proto/src/clj/app/system/config.clj"
              "flags" ("project" "clj") "fn" "load-config" "line" 10
              "method" "invoke" "name"
              "app.system.config$load_config/invoke" "ns"
              "app.system.config" "type" "clj" "var"
              "app.system.config/load-config")
        (dict "class" "clojure.lang.AFn" "file" "AFn.java" "file-url"
              nil "flags" ("tooling" "java") "line" 156 "method"
              "applyToHelper" "name" "clojure.lang.AFn/applyToHelper"
              "type" "java")
        (dict "class" "clojure.lang.AFn" "file" "AFn.java" "file-url"
              nil "flags" ("tooling" "java") "line" 144 "method"
              "applyTo" "name" "clojure.lang.AFn/applyTo" "type"
              "java")
        (dict "class" "clojure.lang.Compiler$InvokeExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("tooling" "java") "line" 3714 "method" "eval" "name"
              "clojure.lang.Compiler$InvokeExpr/eval" "type" "java")
        (dict "class" "clojure.lang.Compiler$InvokeExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("dup" "tooling" "java") "line" 3713 "method" "eval"
              "name" "clojure.lang.Compiler$InvokeExpr/eval" "type"
              "java")
        (dict "class" "clojure.lang.Compiler$DefExpr" "file"
              "Compiler.java" "file-url" nil "flags"
              ("tooling" "java") "line" 457 "method" "eval" "name"
              "clojure.lang.Compiler$DefExpr/eval" "type" "java")
        (dict "class" "clojure.lang.Compiler" "file" "Compiler.java"
              "file-url" nil "flags" ("tooling" "java") "line" 7199
              "method" "eval" "name" "clojure.lang.Compiler/eval"
              "type" "java")
        (dict "class" "clojure.lang.Compiler" "file" "Compiler.java"
              "file-url" nil "flags" ("tooling" "java") "line" 7653
              "method" "load" "name" "clojure.lang.Compiler/load"
              "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("tooling" "java") "line" 381 "method"
              "loadResourceScript" "name"
              "clojure.lang.RT/loadResourceScript" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("dup" "tooling" "java") "line" 372 "method"
              "loadResourceScript" "name"
              "clojure.lang.RT/loadResourceScript" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("tooling" "java") "line" 459 "method"
              "load" "name" "clojure.lang.RT/load" "type" "java")
        (dict "class" "clojure.lang.RT" "file" "RT.java" "file-url"
              nil "flags" ("dup" "tooling" "java") "line" 424 "method"
              "load" "name" "clojure.lang.RT/load" "type" "java")
        (dict "class" "clojure.core$load$fn__6908" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load/fn" "line" 6162 "method"
              "invoke" "name" "clojure.core$load$fn__6908/invoke" "ns"
              "clojure.core" "type" "clj" "var" "clojure.core/load")
        (dict "class" "clojure.core$load" "file" "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load" "line" 6161 "method"
              "invokeStatic" "name" "clojure.core$load/invokeStatic"
              "ns" "clojure.core" "type" "clj" "var"
              "clojure.core/load")
        (dict "class" "clojure.core$load" "file" "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load" "line" 6145 "method"
              "doInvoke" "name" "clojure.core$load/doInvoke" "ns"
              "clojure.core" "type" "clj" "var" "clojure.core/load")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 408
              "method" "invoke" "name" "clojure.lang.RestFn/invoke"
              "type" "java")
        (dict "class" "clojure.core$load_one" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-one" "line" 5934 "method"
              "invokeStatic" "name"
              "clojure.core$load_one/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/load-one")
        (dict "class" "clojure.core$load_one" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-one" "line" 5929 "method"
              "invoke" "name" "clojure.core$load_one/invoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-one")
        (dict "class" "clojure.core$load_lib$fn__6850" "file"
              "core.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib/fn" "line" 5976 "method"
              "invoke" "name" "clojure.core$load_lib$fn__6850/invoke"
              "ns" "clojure.core" "type" "clj" "var"
              "clojure.core/load-lib")
        (dict "class" "clojure.core$load_lib" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib" "line" 5975 "method"
              "invokeStatic" "name"
              "clojure.core$load_lib/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/load-lib")
        (dict "class" "clojure.core$load_lib" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-lib" "line" 5954 "method"
              "doInvoke" "name" "clojure.core$load_lib/doInvoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-lib")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 142
              "method" "applyTo" "name" "clojure.lang.RestFn/applyTo"
              "type" "java")
        (dict "class" "clojure.core$apply" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("tooling" "clj") "fn" "apply" "line" 669
              "method" "invokeStatic" "name"
              "clojure.core$apply/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/apply")
        (dict "class" "clojure.core$load_libs" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-libs" "line" 6017 "method"
              "invokeStatic" "name"
              "clojure.core$load_libs/invokeStatic" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-libs")
        (dict "class" "clojure.core$load_libs" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "load-libs" "line" 6001 "method"
              "doInvoke" "name" "clojure.core$load_libs/doInvoke" "ns"
              "clojure.core" "type" "clj" "var"
              "clojure.core/load-libs")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 137
              "method" "applyTo" "name" "clojure.lang.RestFn/applyTo"
              "type" "java")
        (dict "class" "clojure.core$apply" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("tooling" "clj") "fn" "apply" "line" 669
              "method" "invokeStatic" "name"
              "clojure.core$apply/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/apply")
        (dict "class" "clojure.core$require" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("clj") "fn" "require" "line" 6039 "method"
              "invokeStatic" "name"
              "clojure.core$require/invokeStatic" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/require")
        (dict "class" "clojure.core$require" "file" "core.clj"
              "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/org/clojure/clojure/1.11.3/clojure-1.11.3.jar!/clojure/core.clj"
              "flags" ("dup" "clj") "fn" "require" "line" 6039
              "method" "doInvoke" "name"
              "clojure.core$require/doInvoke" "ns" "clojure.core"
              "type" "clj" "var" "clojure.core/require")
        (dict "class" "clojure.lang.RestFn" "file" "RestFn.java"
              "file-url" nil "flags" ("tooling" "java") "line" 421
              "method" "invoke" "name" "clojure.lang.RestFn/invoke"
              "type" "java")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload-one" "line"
              35 "method" "invokeStatic" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one/invokeStatic"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload-one" "line"
              21 "method" "invoke" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload_one/invoke"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload-one")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload" "line" 52
              "method" "invokeStatic" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload/invokeStatic"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload")
        (dict "class"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload"
              "file" "reload.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/inlined/deps/toolsnamespace/v1v3v0/clojure/tools/namespace/reload.clj"
              "flags" ("tooling" "clj") "fn" "track-reload" "line" 43
              "method" "invoke" "name"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload$track_reload/invoke"
              "ns"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload"
              "type" "clj" "var"
              "cider.nrepl.inlined.deps.toolsnamespace.v1v3v0.clojure.tools.namespace.reload/track-reload")
        (dict "class"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297$fn__129298"
              "file" "refresh.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/middleware/refresh.clj"
              "flags" ("tooling" "clj") "fn" "refresh-reply/fn/fn"
              "line" 101 "method" "invoke" "name"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297$fn__129298/invoke"
              "ns" "cider.nrepl.middleware.refresh" "type" "clj" "var"
              "cider.nrepl.middleware.refresh/refresh-reply")
        (dict "class"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297"
              "file" "refresh.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/cider/cider-nrepl/0.49.2/cider-nrepl-0.49.2.jar!/cider/nrepl/middleware/refresh.clj"
              "flags" ("tooling" "clj") "fn" "refresh-reply/fn" "line"
              91 "method" "invoke" "name"
              "cider.nrepl.middleware.refresh$refresh_reply$fn__129297/invoke"
              "ns" "cider.nrepl.middleware.refresh" "type" "clj" "var"
              "cider.nrepl.middleware.refresh/refresh-reply")
        (dict "class"
              "nrepl.middleware.session$session_exec$session_loop__24462"
              "file" "session.clj" "file-url"
              "jar:file:/Users/rrudakov/.m2/repository/nrepl/nrepl/1.3.0-beta2/nrepl-1.3.0-beta2.jar!/nrepl/middleware/session.clj"
              "flags" ("tooling" "clj") "fn"
              "session-exec/session-loop" "line" 234 "method" "invoke"
              "name"
              "nrepl.middleware.session$session_exec$session_loop__24462/invoke"
              "ns" "nrepl.middleware.session" "type" "clj" "var"
              "nrepl.middleware.session/session-exec")
        (dict "class" "nrepl.SessionThread" "file"
              "SessionThread.java" "file-url" nil "flags"
              ("tooling" "java") "line" 21 "method" "run" "name"
              "nrepl.SessionThread/run" "type" "java"))))
  error-ns   "integration.utils.system"
  status     ("error")
)
(<--
  id         "13"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:39.013753000"
  err        "Execution error (IllegalArgumentException) at nrepl.transpor..."
)
(<--
  id         "13"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:39.015079000"
  status     ("done")
)
(<--
  id                 "13"
  session            "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp         "2024-07-22 14:23:39.016482000"
  changed-namespaces (dict ...)
  repl-type          "clj"
  status             ("state")
)
(-->
  id         "14"
  op         "eldoc"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:42.299266000"
  context    "(__prefix__ test-config-api

  (-> "system/config.edn"
     ..."
  ns         #("integration.utils.system" 0 24 (face font-lock-type-face cider-block-dynamic-font-lock t cider-locals nil fontified t))
  sym        "def"
)
(<--
  id         "14"
  session    "2e9701e5-aa50-46dc-af47-4027a78d95f2"
  time-stamp "2024-07-22 14:23:42.455629000"
  docstring  "Creates and interns a global var with the name
  of symbol i..."
  eldoc      (("def" "symbol" "doc-string?" "init?"))
  name       "def"
  status     ("done")
  type       "special-form"
)
```

</details>

### CIDER version information

```
;; CIDER 1.15.1 (Cogne), nREPL 1.3.0-beta2
;; Clojure 1.11.3, Java 22.0.2
```

### Lein / Clojure CLI version

Clojure CLI 1.11

### Emacs version

GNU Emacs 30.0.60 (build 1, aarch64-apple-darwin23.5.0, NS appkit-2487.60 Version 14.5 (Build 23F79)) of 2024-07-15

### Operating system

MacOS 14

### JDK distribution

```
openjdk version "22.0.2" 2024-07-16
OpenJDK Runtime Environment Homebrew (build 22.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 22.0.2, mixed mode, sharing)
```

**Comment by vemv** [comment]
Thanks for the report!

So you can confirm that merely toggling the `cider-injected-nrepl-version` defcustom is sufficient to repro/workaround the issue, correct?

cc/ @alexander-yakushev

**Comment by vemv** [comment]
> Unfortunately I couldn't reproduce it on a dummy test project, but I can reproduce it consistently on a real project which I cannot share.

Eyeing the stacktraces, that appears to be because Timbre is involved. Perhaps both nrepl and Timbre have some assumption about `*out*`, something like that.

**Comment by rrudakov** [comment]
> So you can confirm that merely toggling the `cider-injected-nrepl-version` defcustom is sufficient to repro/workaround the issue, correct?

I started CIDER with prefix argument and edited nrepl version in the generated command, but I assume changing the mentioned variable has the same effect.

**Comment by rrudakov** [comment]
> > Unfortunately I couldn't reproduce it on a dummy test project, but I can reproduce it consistently on a real project which I cannot share.
> 
> Eyeing the stacktraces, that appears to be because Timbre is involved. Perhaps both nrepl and Timbre have some assumption about `*out*`, something like that.

Hmm, my dummy testing project also has timbre in the dependencies, but I cannot reproduce it there.

**Comment by vemv** [comment]
Stacktrace suggests you have a `user/println-ctx-aware-appender` fn - is that shareable?

**Comment by rrudakov** [comment]
Yes, here it is:

```clojure
(defn println-ctx-aware-appender
  "Adjusted version of built-in timbre println appender which
  additionally prints context data."
  [& [{:keys [stream] :or {stream :auto}}]]
  (let [stream (case stream
                 :std-err timbre/default-err
                 :std-out timbre/default-out
                 stream)]

    {:enabled? true
     :fn
     (fn [data]
       (let [{:keys [output_ context]}
             data

             stream
             (case stream
               :auto  (if (:error-level? data) *err* *out*)
               :*out* *out*
               :*err* *err*
               stream)

             msg
             (if context
               (let [output (force output_)]
                 (if (str/ends-with? output "\n")
                   (str output context)
                   (str output " " context)))
               (force output_))]
         (binding [*out* stream]
           (enc/println-atomic msg))))}))
```

**Comment by rrudakov** [comment]
Looks like I have a minimal example to reproduce the bug:

### `deps.edn`

```clojure
{:paths   ["src" "test"]
 :deps    {com.taoensso/timbre {:mvn/version "6.5.0"}}
 :aliases {:dev {:extra-paths ["env/dev"]}}}
```

### `env/dev/user.clj`

```clojure
(ns user
  (:require
   [taoensso.timbre :as timbre]))

(timbre/info "Test message")
```

Use cider-jack-in with prefix argument and add `:dev` alias to include `user.clj`. 

When CIDER is started use `M-x cider-ns-refresh` or `C-c M-n r`.

**Comment by alexander-yakushev** [comment]
Thank you very much for the report and a simple reproducer! I'm working on a fix.

**Comment by alexander-yakushev** [comment]
Should be fixed in the rolling MELPA CIDER, could you please check?

**Comment by rrudakov** [comment]
@alexander-yakushev thanks for working on this. I've updated CIDER from MELPA, and it tries to use nrepl 1.3.0-beta3, which is not yet available on clojars. I'll test it as soon as it's published.

**Comment by alexander-yakushev** [comment]
Sonatype has been acting up since the morning. I restarted the CI, let's see if this helps.

**Comment by rrudakov** [comment]
It's still not published, but I have installed the latest nrepl locally and I can confirm that the refresh now works without any issues.

**Comment by bbatsov** [comment]
My bad. It's published now.

**Comment by rrudakov** [comment]
Bozhidar Batsov ***@***.***> writes:

> My bad. It's published now. 

Great, thank you. I think this bug can be closed now.
-- 
Best regards, Roman
